### ISSUE TITLE
Integration sync issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/integration-service#109]
https://avni.freshdesk.com/a/tickets/3317

**Comment by himeshr** [comment]
2023-12-15 04:40:35,753 DEBUG SpringTaskScheduler-1 [worker.avni.ActivityWorker] Processing avni subject 788da5d8-b7bd-4993-bf50-125e4e2dedae
2023-12-15 04:40:35,759 INFO  SpringTaskScheduler-1 [goonj.repository.GoonjBaseRepository] Request body:{"Activities":[{"SourceId":"788da5d8-b7bd-4993-bf50-125e4e2dedae","State":"Maharashtra","District":"Palghar","Block":"Palghar","LocalityVillageName":"Mendhwan","tolaMohalla":"Patilpada ","CreatedBy":"milindmnvs@goonj","ModifiedBy":"salesforce_system_user@goonj","nameOfAccount":"Goonj Palghar","TypeofInitiative":"CFW","ActivityStartDate":"2023-11-29","ActivityEndDate":"2023-11-30","ActivityType":"Water_Management","ActivitySubType":"Check dam","ActivityCategory":"Making","NoofWorkingDays":2,"NoofparticipantsMaleCFW":5,"NoofparticipantsFemaleCFW":26,"NoofparticipantsMaleNJPC":0,"NoofparticipantsFemaleNJPC":0,"NoofparticipantsNJPCOther":0,"ObjectiveofCFWwork":"Shortage of water in the village","MeasurementType":"Volume","DepthHeight":3,"Diameter":0,"Length":28,"Breadth":3,"BeforeImplementationPhotograph":"https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/639b4216-8f19-4c5c-9e38-c2b6136d87c3.jpg;https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/5b6f4b0a-017d-44b9-9055-f2b35dc50d47.jpg;https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/1c9172e1-2e29-4b3d-9ed7-ffc01060a26f.jpg","DuringImplementationPhotograph":"https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/16487e9f-fcec-44be-b343-407c8e39e1df.jpg;https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/f3ff4917-40c9-4297-b639-3e1080187e96.jpg;https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/51087d2c-0364-481e-ab13-88cb064421ce.jpg;https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/6e958eeb-dbcb-4204-904c-ad647bffdcf4.jpg;https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/6e958eeb-dbcb-4204-904c-ad647bffdcf4.jpg","AfterImplementationPhotograph":"https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/2dd0a371-4980-4c10-b463-d5856b22ff33.jpg;https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/0dc18da1-b91f-4951-a2b2-0e11ee9ffee8.jpg;https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/4d4e226c-f9c4-4b98-81e8-7baec438410a.jpg","NoofparticipantsCFWOther":0}]}
2023-12-15 04:40:35,760 DEBUG SpringTaskScheduler-1 [goonj.service.TokenService] Token still valid
2023-12-15 04:40:35,920 DEBUG SpringTaskScheduler-1 [worker.avni.ActivityWorker] ActivityId null synced successfully.
2023-12-15 04:40:35,931 DEBUG SpringTaskScheduler-1 [worker.avni.ActivityWorker] Processing avni subject e3163b98-ac55-44fd-b91d-a8040837fb7a
2023-12-15 04:40:35,936 ERROR SpringTaskScheduler-1 [worker.avni.ActivityWorker] Avni subject e3163b98-ac55-44fd-b91d-a8040837fb7a could not be synced to Goonj Salesforce.
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.avni_integration_service.goonj.repository.ActivityRepository.createActivityRequest(ActivityRepository.java:125)
	at org.avni_integration_service.goonj.repository.ActivityRepository.convertSubjectToActivityRequest(ActivityRepository.java:71)
	at org.avni_integration_service.goonj.repository.ActivityRepository.createEvent(ActivityRepository.java:59)
	at org.avni_integration_service.goonj.worker.avni.SubjectWorker.syncSubjectToGoonj(SubjectWorker.java:135)
	at org.avni_integration_service.goonj.worker.avni.ActivityWorker.processActivityEvent(ActivityWorker.java:45)
	at org.avni_integration_service.goonj.worker.avni.ActivityWorker.createSubject(ActivityWorker.java:42)
	at org.avni_integration_service.goonj.worker.avni.SubjectWorker.processSubject(SubjectWorker.java:112)
	at org.avni_integration_service.goonj.worker.avni.SubjectWorker.processSubjects(SubjectWorker.java:68)
	at org.avni_integration_service.goonj.worker.avni.ActivityWorker.process(ActivityWorker.java:38)
	at org.avni_integration_service.goonj.job.AvniGoonjMainJob.processActivity(AvniGoonjMainJob.java:141)
	at org.avni_integration_service.goonj.job.AvniGoonjMainJob.execute(AvniGoonjMainJob.java:76)
	at org.avni_integration_service.scheduler.IntegrationJobScheduler.lambda$scheduleAll$0(IntegrationJobScheduler.java:81)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by himeshr** [comment]
Minor casting done, no need for review or QA.

**Comment by himeshr** [comment]
ALready deployed and verified that ssystem recovers for the entities with this error.
