### ISSUE TITLE
Bugsnag Error Goonj Integration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/integration-service#71]
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-int/errors/6494217fce662c0007320211

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error: "[{"errorCode":"APEX_ERROR","message":"System.StringException: Invalid id: dis-sta-id-01\n\nClass.DispatchReceivedService.upsertDispatchReceivedStatus: line 52, column 1"}]"
        at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:100)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:751)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:651)
        at org.avni_integration_service.goonj.repository.GoonjBaseRepository.createSingleEntity(GoonjBaseRepository.java:87)
        at org.avni_integration_service.goonj.repository.DispatchReceiptRepository.createEvent(DispatchReceiptRepository.java:69)
        at org.avni_integration_service.goonj.worker.avni.GeneralEncounterWorker.syncEncounterToGoonj(GeneralEncounterWorker.java:143)
        at org.avni_integration_service.goonj.worker.avni.DispatchReceiptWorker.processDispatchReceiptEvent(DispatchReceiptWorker.java:46)
        at org.avni_integration_service.goonj.worker.avni.DispatchReceiptWorker.createOrUpdateGeneralEncounter(DispatchReceiptWorker.java:43)
        at org.avni_integration_service.goonj.worker.avni.GeneralEncounterWorker.processGeneralEncounter(GeneralEncounterWorker.java:122)
        at org.avni_integration_service.goonj.worker.avni.GeneralEncounterWorker.processEncounters(GeneralEncounterWorker.java:71)
        at org.avni_integration_service.goonj.worker.avni.DispatchReceiptWorker.process(DispatchReceiptWorker.java:39)
        at org.avni_integration_service.goonj.job.AvniGoonjMainJob.processDispatchReceiptAndDistribution(AvniGoonjMainJob.java:133)
        at org.avni_integration_service.goonj.job.AvniGoonjMainJob.execute(AvniGoonjMainJob.java:75)
        at org.avni_integration_service.scheduler.IntegrationJobScheduler.mainGoonjJob(IntegrationJobScheduler.java:47)
        at jdk.internal.reflect.GeneratedMethodAccessor172.invoke(Unknown:-1)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)

**Comment by himeshr** [comment]
Unable to find the culprit data entity causing this error.
Closing this as its Not Reproducible.
